var Sound = require('react-native-sound');

export function dinosourList(){
    dinosours = [
            {
                'id':1,
                'name':'Anklosaurus',
                'alphabet': 'A',
                'sound': 'sound.mp3',
                'image': require('../assests/images/ankylosaurus1.png'),
                'pronunciation': 'an-KIE-loh-sore-us',
                'sound': initSound('a.m4a'),
                'description': 'One of the largest armoured dinosaurus, Ankylosaurus had a wide, heavily armoured skull and a large tail club. It had a large gut space for digesting plant material.'
            },
            {
                'id':2,
                'name':'Brachiosaurus',
                'alphabet': 'B',
                'sound': 'sound.mp3',
                'image': require('../assests/images/ankylosaurus2.png'),
                'pronunciation': 'BRAK-ee-oh-sore-us',
                'sound': initSound('a.m4a'),
                'description': 'Brachiosaurus held its head very high. It is likely to have eaten the leaves on tall tree-like plants.'
            },
            {
                'id':3,
                'name':'Confuciusornis',
                'alphabet': 'C',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'kon-few-shus-or-niss',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': 'It is the oldest known bird to have a beak.It was named after the Chinese moral philosopher Confucius (551–479 BC). Confuciusornis is one of the most abundant vertebrates found in the Yixian Formation'
            },
            {
                'id':4,
                'name':'Dacentrurus',
                'alphabet': 'D',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'dah-sen-troo-russ',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': 'Although Dacentrurus is considered to have the same proportions as Stegosaurus, its plate and spike configuration is known to be rather different, as it probably had both two rows of small plates on its neck and two rows of longer spikes along its tail.'
            },
            {
                'id':5,
                'name':'Einiosaurus',
                'alphabet': 'E',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'ie-nee-oh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': 'The nasal horn of Einiosaurus is quite unusual in that it curves forward to point towards the ground,‭ ‬something which is reflected in the species name E.‭ ‬procurvicornis which translates to English as‭ "forward curving horn‭".‭ '
            },
            {
                'id':6,
                'name':'Fukuisaurus',
                'alphabet': 'F',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'foo-koo-I-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': 'Fukuisaurus is only known from a skull, so the rest of the reconstruction is guesswork based on similar dinosaurs.',
            },    
            {
                'id':7,
                'name':'Graciliceratops',
                'alphabet': 'G',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'gras-i-li-serra-tops',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': 'Like other ceratopsians, Graciliceratops would have been an herbivore, using its powerful beak and shearing teeth to process tough plant matter. Little is known about the flora of the ancient Gobi Desert, and so it is unclear what it would have eaten.',
            },
            {
                'id':8,
                'name':'Hagryphus',
                'alphabet': 'H',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'ha-grif-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': 'Hagryphus is known from only a left hand, fragmentary metatarsals and pedal phalanges (part of a foot), so this reconstruction is based on these and Chirostenotes, a very similar dinosaur.',
            },
            {
                'id':9,
                'name':'Irritator',
                'alphabet': 'I',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'irr-it-ate-or',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': 'Irritator was quite like Spinosaurus. It is known only from a skull, so the sail is a guess.',
            },    
            {
                'id':10,
                'name':'Jaxartosaurus',
                'alphabet': 'J',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'jak-sahr-toh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':11,
                'name':'Kentrosaurus',
                'alphabet': 'K',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'ken-TROH-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':12,
                'name':'Lambeosaurus',
                'alphabet': 'L',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'lam-BEE-oh-SORE-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },    
            {
                'id':13,
                'name':'Maiasaura',
                'alphabet': 'M',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'my-ah-SORE-ah',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':14,
                'name':'Nodosaurus',
                'alphabet': 'N',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'no-doh-SORE-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':15,
                'name':'Orodromeus',
                'alphabet': 'O',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'or-oh-DROM-ee-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':16,
                'name':'Parasaurolophus',
                'alphabet': 'P',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'pa-ra-saw-ROL-off-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':17,
                'name':'Quaesitosaurus',
                'alphabet': 'Q',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'kwee-siet-oh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':18,
                'name':'Rinchenia',
                'alphabet': 'R',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'rin-chen-ee-ah',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':19,
                'name':'Stegosaurus',
                'alphabet': 'S',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'STEG-oh-SORE-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':20,
                'name':'Tyrannosaurus',
                'alphabet': 'T',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'tie-RAN-oh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':21,
                'name':'Urbacodon',
                'alphabet': 'U',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'urb-ah-ko-don',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },    
            {
                'id':22,
                'name':'Velociraptor',
                'alphabet': 'V',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'vel-OSS-ee-rap-tor',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':23,
                'name':'Wuerhosaurus',
                'alphabet': 'W',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'woo-uhr-huh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },
            {
                'id':24,
                'name':'Xenoceratops',
                'alphabet': 'X',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'Xenoceratops',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },    
            {
                'id':25,
                'name':'Yinlong',
                'alphabet': 'Y',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'yin-long',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            }, 
            {
                'id':26,
                'name':'Zalmoxes',
                'alphabet': 'Z',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'zal-moks-eez',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
                'description': '',
            },              
            ]

            return dinosours
}
function initSound(sound){
    const s = new Sound(sound, Sound.MAIN_BUNDLE, (error) => {
        if (error) {
            alert('failed to load the sound', error);
        } else {
                        // have to put the call to play() in the onload callback
        }
    })
    return s
}