var Sound = require('react-native-sound');

export function dinosourList(){
    dinosours = [
            {
                'id':1,
                'name':'Anklosaurus',
                'alphabet': 'A',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'an-KIE-loh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':2,
                'name':'Brachiosaurus',
                'alphabet': 'B',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'BRAK-ee-oh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':3,
                'name':'Confuciusornis',
                'alphabet': 'C',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'kon-few-shus-or-niss',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':4,
                'name':'Dacentrurus',
                'alphabet': 'D',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'dah-sen-troo-russ',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':5,
                'name':'Einiosaurus',
                'alphabet': 'E',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'ie-nee-oh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':6,
                'name':'Fukuisaurus',
                'alphabet': 'F',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'foo-koo-I-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },    
            {
                'id':7,
                'name':'Graciliceratops',
                'alphabet': 'G',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'gras-i-li-serra-tops',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':8,
                'name':'Hagryphus',
                'alphabet': 'H',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'ha-grif-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':9,
                'name':'Irritator',
                'alphabet': 'I',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'irr-it-ate-or',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },    
            {
                'id':10,
                'name':'Jaxartosaurus',
                'alphabet': 'J',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'jak-sahr-toh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':11,
                'name':'Kentrosaurus',
                'alphabet': 'K',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'ken-TROH-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':12,
                'name':'Lambeosaurus',
                'alphabet': 'L',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'lam-BEE-oh-SORE-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },    
            {
                'id':13,
                'name':'Maiasaura',
                'alphabet': 'M',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'my-ah-SORE-ah',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':14,
                'name':'Nodosaurus',
                'alphabet': 'N',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'no-doh-SORE-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':15,
                'name':'Orodromeus',
                'alphabet': 'O',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'or-oh-DROM-ee-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':16,
                'name':'Parasaurolophus',
                'alphabet': 'P',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'pa-ra-saw-ROL-off-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':17,
                'name':'Quaesitosaurus',
                'alphabet': 'Q',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'kwee-siet-oh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':18,
                'name':'Rinchenia',
                'alphabet': 'R',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'rin-chen-ee-ah',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':19,
                'name':'Stegosaurus',
                'alphabet': 'S',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'STEG-oh-SORE-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':20,
                'name':'Tyrannosaurus',
                'alphabet': 'T',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'tie-RAN-oh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':21,
                'name':'Urbacodon',
                'alphabet': 'U',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'urb-ah-ko-don',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },    
            {
                'id':22,
                'name':'Velociraptor',
                'alphabet': 'V',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'vel-OSS-ee-rap-tor',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':23,
                'name':'Wuerhosaurus',
                'alphabet': 'W',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour2.jpg'),
                'pronunciation': 'woo-uhr-huh-sore-us',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },
            {
                'id':24,
                'name':'Xenoceratops',
                'alphabet': 'X',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'Xenoceratops',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },    
            {
                'id':25,
                'name':'Yinlong',
                'alphabet': 'Y',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'yin-long',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            }, 
            {
                'id':26,
                'name':'Zalmoxes',
                'alphabet': 'Z',
                'sound': 'sound.mp3',
                'image': require('../assests/images/dinosour.jpg'),
                'pronunciation': 'zal-moks-eez',
                'sound': initSound('SampleAudio_0.4mb.mp3'),
            },              
            ]

            return dinosours
}
function initSound(sound){
    const s = new Sound(sound, Sound.MAIN_BUNDLE, (error) => {
        if (error) {
            alert('failed to load the sound', error);
        } else {
                        // have to put the call to play() in the onload callback
        }
    })
    return s
}